// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'types.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BarcodeModuleSettings _$BarcodeModuleSettingsFromJson(
  Map<String, dynamic> json,
) => BarcodeModuleSettings(
  presenceMandatory: json['presenceMandatory'] as bool? ?? false,
  barcodeImageReturnEnabled:
      json['barcodeImageReturnEnabled'] as bool? ?? false,
  pdf417ScanningEnabled: json['pdf417ScanningEnabled'] as bool? ?? true,
  qrScanningEnabled: json['qrScanningEnabled'] as bool? ?? true,
  upceScanningEnabled: json['upceScanningEnabled'] as bool? ?? false,
  upcaScanningEnabled: json['upcaScanningEnabled'] as bool? ?? false,
  code128ScanningEnabled: json['code128ScanningEnabled'] as bool? ?? false,
  code39ScanningEnabled: json['code39ScanningEnabled'] as bool? ?? false,
  ean8ScanningEnabled: json['ean8ScanningEnabled'] as bool? ?? false,
  ean13ScanningEnabled: json['ean13ScanningEnabled'] as bool? ?? false,
  itfScanningEnabled: json['itfScanningEnabled'] as bool? ?? false,
  dataMatrixScanningEnabled:
      json['dataMatrixScanningEnabled'] as bool? ?? false,
  aztecScanningEnabled: json['aztecScanningEnabled'] as bool? ?? false,
);

Map<String, dynamic> _$BarcodeModuleSettingsToJson(
  BarcodeModuleSettings instance,
) => <String, dynamic>{
  'presenceMandatory': instance.presenceMandatory,
  'barcodeImageReturnEnabled': instance.barcodeImageReturnEnabled,
  'pdf417ScanningEnabled': instance.pdf417ScanningEnabled,
  'qrScanningEnabled': instance.qrScanningEnabled,
  'upceScanningEnabled': instance.upceScanningEnabled,
  'upcaScanningEnabled': instance.upcaScanningEnabled,
  'code128ScanningEnabled': instance.code128ScanningEnabled,
  'code39ScanningEnabled': instance.code39ScanningEnabled,
  'ean8ScanningEnabled': instance.ean8ScanningEnabled,
  'ean13ScanningEnabled': instance.ean13ScanningEnabled,
  'itfScanningEnabled': instance.itfScanningEnabled,
  'dataMatrixScanningEnabled': instance.dataMatrixScanningEnabled,
  'aztecScanningEnabled': instance.aztecScanningEnabled,
};

DocumentCaptureModuleSettings _$DocumentCaptureModuleSettingsFromJson(
  Map<String, dynamic> json,
) => DocumentCaptureModuleSettings(
  cropType:
      $enumDecodeNullable(_$InputImageCropTypeEnumMap, json['cropType']) ??
      InputImageCropType.notCropped,
  unsupportedDocumentsAllowed:
      json['unsupportedDocumentsAllowed'] as bool? ?? false,
  secondSideWithNoExtractableDataSkipped:
      json['secondSideWithNoExtractableDataSkipped'] as bool? ?? true,
  passportDataPageScanOnly: json['passportDataPageScanOnly'] as bool? ?? true,
  faceImageExtractionEnabled:
      json['faceImageExtractionEnabled'] as bool? ?? false,
  faceImagePresenceMandatory:
      json['faceImagePresenceMandatory'] as bool? ?? false,
  inputImageReturnEnabled: json['inputImageReturnEnabled'] as bool? ?? false,
  documentImageReturnEnabled:
      json['documentImageReturnEnabled'] as bool? ?? false,
  inputImageMargin: (json['inputImageMargin'] as num?)?.toDouble(),
  dotsPerInch: (json['dotsPerInch'] as num?)?.toInt() ?? 250,
  extensionFactor: (json['extensionFactor'] as num?)?.toDouble() ?? 0.0,
  blurSensitivityLevel:
      $enumDecodeNullable(
        _$SensitivityLevelEnumMap,
        json['blurSensitivityLevel'],
      ) ??
      SensitivityLevel.mid,
  imageWithBlurRejected: json['imageWithBlurRejected'] as bool?,
  glareSensitivityLevel:
      $enumDecodeNullable(
        _$SensitivityLevelEnumMap,
        json['glareSensitivityLevel'],
      ) ??
      SensitivityLevel.mid,
  imageWithGlareRejected: json['imageWithGlareRejected'] as bool?,
  tiltSensitivityLevel:
      $enumDecodeNullable(
        _$SensitivityLevelEnumMap,
        json['tiltSensitivityLevel'],
      ) ??
      SensitivityLevel.mid,
  imageWithPoorLightingRejected:
      json['imageWithPoorLightingRejected'] as bool? ?? true,
  imageWithHandOcclusionRejected:
      json['imageWithHandOcclusionRejected'] as bool?,
  inputImageSelectionStrategy:
      $enumDecodeNullable(
        _$InputImageSelectionStrategyEnumMap,
        json['inputImageSelectionStrategy'],
      ) ??
      InputImageSelectionStrategy.balanced,
);

Map<String, dynamic> _$DocumentCaptureModuleSettingsToJson(
  DocumentCaptureModuleSettings instance,
) => <String, dynamic>{
  'cropType': _$InputImageCropTypeEnumMap[instance.cropType]!,
  'unsupportedDocumentsAllowed': instance.unsupportedDocumentsAllowed,
  'secondSideWithNoExtractableDataSkipped':
      instance.secondSideWithNoExtractableDataSkipped,
  'passportDataPageScanOnly': instance.passportDataPageScanOnly,
  'faceImageExtractionEnabled': instance.faceImageExtractionEnabled,
  'faceImagePresenceMandatory': instance.faceImagePresenceMandatory,
  'inputImageReturnEnabled': instance.inputImageReturnEnabled,
  'documentImageReturnEnabled': instance.documentImageReturnEnabled,
  'inputImageMargin': instance.inputImageMargin,
  'dotsPerInch': instance.dotsPerInch,
  'extensionFactor': instance.extensionFactor,
  'blurSensitivityLevel':
      _$SensitivityLevelEnumMap[instance.blurSensitivityLevel]!,
  'imageWithBlurRejected': instance.imageWithBlurRejected,
  'glareSensitivityLevel':
      _$SensitivityLevelEnumMap[instance.glareSensitivityLevel]!,
  'imageWithGlareRejected': instance.imageWithGlareRejected,
  'tiltSensitivityLevel':
      _$SensitivityLevelEnumMap[instance.tiltSensitivityLevel]!,
  'imageWithPoorLightingRejected': instance.imageWithPoorLightingRejected,
  'imageWithHandOcclusionRejected': instance.imageWithHandOcclusionRejected,
  'inputImageSelectionStrategy':
      _$InputImageSelectionStrategyEnumMap[instance
          .inputImageSelectionStrategy]!,
};

const _$InputImageCropTypeEnumMap = {
  InputImageCropType.notCropped: 'notCropped',
  InputImageCropType.unknown: 'unknown',
  InputImageCropType.cropped: 'cropped',
};

const _$SensitivityLevelEnumMap = {
  SensitivityLevel.off: 'off',
  SensitivityLevel.low: 'low',
  SensitivityLevel.mid: 'mid',
  SensitivityLevel.high: 'high',
};

const _$InputImageSelectionStrategyEnumMap = {
  InputImageSelectionStrategy.singleImage: 'singleImage',
  InputImageSelectionStrategy.optimizeForSpeed: 'optimizeForSpeed',
  InputImageSelectionStrategy.balanced: 'balanced',
  InputImageSelectionStrategy.optimizeForQuality: 'optimizeForQuality',
};

MrzModuleSettings _$MrzModuleSettingsFromJson(Map<String, dynamic> json) =>
    MrzModuleSettings(
      presenceMandatory: json['presenceMandatory'] as bool? ?? false,
    );

Map<String, dynamic> _$MrzModuleSettingsToJson(MrzModuleSettings instance) =>
    <String, dynamic>{'presenceMandatory': instance.presenceMandatory};

VizModuleSettings _$VizModuleSettingsFromJson(Map<String, dynamic> json) =>
    VizModuleSettings(
      presenceMandatory: json['presenceMandatory'] as bool? ?? false,
      signatureImageExtractionEnabled:
          json['signatureImageExtractionEnabled'] as bool? ?? false,
      characterValidationEnabled:
          json['characterValidationEnabled'] as bool? ?? true,
      resultAggregationEnabled: json['resultAggregationEnabled'] as bool?,
    );

Map<String, dynamic> _$VizModuleSettingsToJson(
  VizModuleSettings instance,
) => <String, dynamic>{
  'presenceMandatory': instance.presenceMandatory,
  'signatureImageExtractionEnabled': instance.signatureImageExtractionEnabled,
  'characterValidationEnabled': instance.characterValidationEnabled,
  'resultAggregationEnabled': instance.resultAggregationEnabled,
};

ClassFilter _$ClassFilterFromJson(Map<String, dynamic> json) => ClassFilter()
  ..includeDocuments = (json['includeDocuments'] as List<dynamic>?)
      ?.map((e) => DocumentFilter.fromJson(e as Map<String, dynamic>))
      .toList()
  ..excludeDocuments = (json['excludeDocuments'] as List<dynamic>?)
      ?.map((e) => DocumentFilter.fromJson(e as Map<String, dynamic>))
      .toList();

Map<String, dynamic> _$ClassFilterToJson(ClassFilter instance) =>
    <String, dynamic>{
      'includeDocuments': instance.includeDocuments
          ?.map((e) => e.toJson())
          .toList(),
      'excludeDocuments': instance.excludeDocuments
          ?.map((e) => e.toJson())
          .toList(),
    };

RedactionSettings _$RedactionSettingsFromJson(Map<String, dynamic> json) =>
    RedactionSettings(
      fields: (json['fields'] as List<dynamic>)
          .map((e) => $enumDecode(_$FieldTypeEnumMap, e))
          .toList(),
      mode:
          $enumDecodeNullable(_$RedactionModeEnumMap, json['mode']) ??
          RedactionMode.fullResult,
      documentNumberRedactionSettings:
          json['documentNumberRedactionSettings'] == null
          ? null
          : DocumentNumberRedactionSettings.fromJson(
              json['documentNumberRedactionSettings'] as Map<String, dynamic>,
            ),
      redactBarcodeResult: json['redactBarcodeResult'] as bool? ?? false,
      redactMrzResult: json['redactMrzResult'] as bool? ?? false,
      documentFilter: (json['documentFilter'] as List<dynamic>?)
          ?.map((e) => DocumentFilter.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$RedactionSettingsToJson(
  RedactionSettings instance,
) => <String, dynamic>{
  'mode': _$RedactionModeEnumMap[instance.mode]!,
  'fields': instance.fields.map((e) => _$FieldTypeEnumMap[e]!).toList(),
  'documentNumberRedactionSettings': instance.documentNumberRedactionSettings
      ?.toJson(),
  'redactMrzResult': instance.redactMrzResult,
  'redactBarcodeResult': instance.redactBarcodeResult,
  'documentFilter': instance.documentFilter?.map((e) => e.toJson()).toList(),
};

const _$FieldTypeEnumMap = {
  FieldType.additionalAddressInformation: 'additionalAddressInformation',
  FieldType.additionalNameInformation: 'additionalNameInformation',
  FieldType.additionalOptionalAddressInformation:
      'additionalOptionalAddressInformation',
  FieldType.additionalPersonalIdNumber: 'additionalPersonalIdNumber',
  FieldType.address: 'address',
  FieldType.classEffectiveDate: 'classEffectiveDate',
  FieldType.classExpiryDate: 'classExpiryDate',
  FieldType.conditions: 'conditions',
  FieldType.dateOfBirth: 'dateOfBirth',
  FieldType.dateOfExpiry: 'dateOfExpiry',
  FieldType.dateOfIssue: 'dateOfIssue',
  FieldType.documentAdditionalNumber: 'documentAdditionalNumber',
  FieldType.documentOptionalAdditionalNumber:
      'documentOptionalAdditionalNumber',
  FieldType.documentNumber: 'documentNumber',
  FieldType.employer: 'employer',
  FieldType.endorsements: 'endorsements',
  FieldType.fathersName: 'fathersName',
  FieldType.firstName: 'firstName',
  FieldType.fullName: 'fullName',
  FieldType.issuingAuthority: 'issuingAuthority',
  FieldType.lastName: 'lastName',
  FieldType.licenceType: 'licenceType',
  FieldType.localizedName: 'localizedName',
  FieldType.maritalStatus: 'maritalStatus',
  FieldType.mothersName: 'mothersName',
  FieldType.mrz: 'mrz',
  FieldType.nationality: 'nationality',
  FieldType.personalIdNumber: 'personalIdNumber',
  FieldType.placeOfBirth: 'placeOfBirth',
  FieldType.profession: 'profession',
  FieldType.race: 'race',
  FieldType.religion: 'religion',
  FieldType.residentialStatus: 'residentialStatus',
  FieldType.restrictions: 'restrictions',
  FieldType.sex: 'sex',
  FieldType.vehicleClass: 'vehicleClass',
  FieldType.bloodType: 'bloodType',
  FieldType.sponsor: 'sponsor',
  FieldType.visaType: 'visaType',
  FieldType.documentSubtype: 'documentSubtype',
  FieldType.remarks: 'remarks',
  FieldType.residencePermitType: 'residencePermitType',
  FieldType.manufacturingYear: 'manufacturingYear',
  FieldType.vehicleType: 'vehicleType',
  FieldType.dependentDateOfBirth: 'dependentDateOfBirth',
  FieldType.dependentSex: 'dependentSex',
  FieldType.dependentDocumentNumber: 'dependentDocumentNumber',
  FieldType.dependentFullName: 'dependentFullName',
  FieldType.eligibilityCategory: 'eligibilityCategory',
  FieldType.specificDocumentValidity: 'specificDocumentValidity',
  FieldType.vehicleOwner: 'vehicleOwner',
  FieldType.nationalInsuranceNumber: 'nationalInsuranceNumber',
  FieldType.countryCode: 'countryCode',
  FieldType.certificateNumber: 'certificateNumber',
  FieldType.municipalityOfRegistration: 'municipalityOfRegistration',
  FieldType.localityCode: 'localityCode',
  FieldType.maidenName: 'maidenName',
  FieldType.stateCode: 'stateCode',
  FieldType.dateOfEntry: 'dateOfEntry',
  FieldType.municipalityCode: 'municipalityCode',
  FieldType.pollingStationCode: 'pollingStationCode',
  FieldType.sectionCode: 'sectionCode',
  FieldType.registrationCenterCode: 'registrationCenterCode',
  FieldType.stateName: 'stateName',
  FieldType.effectiveDate: 'effectiveDate',
  FieldType.parentsLastName: 'parentsLastName',
  FieldType.parentsFirstName: 'parentsFirstName',
  FieldType.workRestriction: 'workRestriction',
  FieldType.socialSecurityStatus: 'socialSecurityStatus',
  FieldType.legalStatus: 'legalStatus',
  FieldType.husbandName: 'husbandName',
  FieldType.cardAccessNumber: 'cardAccessNumber',
  FieldType.parentFullName: 'parentFullName',
  FieldType.ethnicity: 'ethnicity',
};

const _$RedactionModeEnumMap = {
  RedactionMode.none: 'none',
  RedactionMode.imageOnly: 'imageOnly',
  RedactionMode.resultFieldsOnly: 'resultFieldsOnly',
  RedactionMode.fullResult: 'fullResult',
};

RedactionSettingsResolver _$RedactionSettingsResolverFromJson(
  Map<String, dynamic> json,
) => RedactionSettingsResolver(
  (json['documentRedactionList'] as List<dynamic>)
      .map((e) => RedactionSettings.fromJson(e as Map<String, dynamic>))
      .toList(),
);

Map<String, dynamic> _$RedactionSettingsResolverToJson(
  RedactionSettingsResolver instance,
) => <String, dynamic>{
  'documentRedactionList': instance.documentRedactionList
      .map((e) => e.toJson())
      .toList(),
};

DetailedFieldType _$DetailedFieldTypeFromJson(Map<String, dynamic> json) =>
    DetailedFieldType(
      $enumDecode(_$FieldTypeEnumMap, json['fieldType']),
      $enumDecode(_$AlphabetTypeEnumMap, json['alphabetType']),
    );

Map<String, dynamic> _$DetailedFieldTypeToJson(DetailedFieldType instance) =>
    <String, dynamic>{
      'fieldType': _$FieldTypeEnumMap[instance.fieldType]!,
      'alphabetType': _$AlphabetTypeEnumMap[instance.alphabetType]!,
    };

const _$AlphabetTypeEnumMap = {
  AlphabetType.latin: 'latin',
  AlphabetType.arabic: 'arabic',
  AlphabetType.cyrillic: 'cyrillic',
  AlphabetType.greek: 'greek',
};

DocumentFilter _$DocumentFilterFromJson(Map<String, dynamic> json) =>
    DocumentFilter(
      country: $enumDecodeNullable(_$CountryIdEnumMap, json['country']),
      region: $enumDecodeNullable(_$RegionIdEnumMap, json['region']),
      documentType: $enumDecodeNullable(
        _$DocumentTypeIdEnumMap,
        json['documentType'],
      ),
    );

Map<String, dynamic> _$DocumentFilterToJson(DocumentFilter instance) =>
    <String, dynamic>{
      'country': _$CountryIdEnumMap[instance.country],
      'region': _$RegionIdEnumMap[instance.region],
      'documentType': _$DocumentTypeIdEnumMap[instance.documentType],
    };

const _$CountryIdEnumMap = {
  CountryId.none: 'none',
  CountryId.albania: 'albania',
  CountryId.algeria: 'algeria',
  CountryId.argentina: 'argentina',
  CountryId.australia: 'australia',
  CountryId.austria: 'austria',
  CountryId.azerbaijan: 'azerbaijan',
  CountryId.bahrain: 'bahrain',
  CountryId.bangladesh: 'bangladesh',
  CountryId.belgium: 'belgium',
  CountryId.bosniaAndHerzegovina: 'bosniaAndHerzegovina',
  CountryId.brunei: 'brunei',
  CountryId.bulgaria: 'bulgaria',
  CountryId.cambodia: 'cambodia',
  CountryId.canada: 'canada',
  CountryId.chile: 'chile',
  CountryId.colombia: 'colombia',
  CountryId.costaRica: 'costaRica',
  CountryId.croatia: 'croatia',
  CountryId.cyprus: 'cyprus',
  CountryId.czechia: 'czechia',
  CountryId.denmark: 'denmark',
  CountryId.dominicanRepublic: 'dominicanRepublic',
  CountryId.egypt: 'egypt',
  CountryId.estonia: 'estonia',
  CountryId.finland: 'finland',
  CountryId.france: 'france',
  CountryId.georgia: 'georgia',
  CountryId.germany: 'germany',
  CountryId.ghana: 'ghana',
  CountryId.greece: 'greece',
  CountryId.guatemala: 'guatemala',
  CountryId.hongKong: 'hongKong',
  CountryId.hungary: 'hungary',
  CountryId.india: 'india',
  CountryId.indonesia: 'indonesia',
  CountryId.ireland: 'ireland',
  CountryId.israel: 'israel',
  CountryId.italy: 'italy',
  CountryId.jordan: 'jordan',
  CountryId.kazakhstan: 'kazakhstan',
  CountryId.kenya: 'kenya',
  CountryId.kosovo: 'kosovo',
  CountryId.kuwait: 'kuwait',
  CountryId.latvia: 'latvia',
  CountryId.lithuania: 'lithuania',
  CountryId.malaysia: 'malaysia',
  CountryId.maldives: 'maldives',
  CountryId.malta: 'malta',
  CountryId.mauritius: 'mauritius',
  CountryId.mexico: 'mexico',
  CountryId.morocco: 'morocco',
  CountryId.netherlands: 'netherlands',
  CountryId.newZealand: 'newZealand',
  CountryId.nigeria: 'nigeria',
  CountryId.pakistan: 'pakistan',
  CountryId.panama: 'panama',
  CountryId.paraguay: 'paraguay',
  CountryId.philippines: 'philippines',
  CountryId.poland: 'poland',
  CountryId.portugal: 'portugal',
  CountryId.puertoRico: 'puertoRico',
  CountryId.qatar: 'qatar',
  CountryId.romania: 'romania',
  CountryId.russia: 'russia',
  CountryId.saudiArabia: 'saudiArabia',
  CountryId.serbia: 'serbia',
  CountryId.singapore: 'singapore',
  CountryId.slovakia: 'slovakia',
  CountryId.slovenia: 'slovenia',
  CountryId.southAfrica: 'southAfrica',
  CountryId.spain: 'spain',
  CountryId.sweden: 'sweden',
  CountryId.switzerland: 'switzerland',
  CountryId.taiwan: 'taiwan',
  CountryId.thailand: 'thailand',
  CountryId.tunisia: 'tunisia',
  CountryId.turkey: 'turkey',
  CountryId.uae: 'uae',
  CountryId.uganda: 'uganda',
  CountryId.uk: 'uk',
  CountryId.ukraine: 'ukraine',
  CountryId.usa: 'usa',
  CountryId.vietnam: 'vietnam',
  CountryId.brazil: 'brazil',
  CountryId.norway: 'norway',
  CountryId.oman: 'oman',
  CountryId.ecuador: 'ecuador',
  CountryId.elSalvador: 'elSalvador',
  CountryId.sriLanka: 'sriLanka',
  CountryId.peru: 'peru',
  CountryId.uruguay: 'uruguay',
  CountryId.bahamas: 'bahamas',
  CountryId.bermuda: 'bermuda',
  CountryId.bolivia: 'bolivia',
  CountryId.china: 'china',
  CountryId.europeanUnion: 'europeanUnion',
  CountryId.haiti: 'haiti',
  CountryId.honduras: 'honduras',
  CountryId.iceland: 'iceland',
  CountryId.japan: 'japan',
  CountryId.luxembourg: 'luxembourg',
  CountryId.montenegro: 'montenegro',
  CountryId.nicaragua: 'nicaragua',
  CountryId.southKorea: 'southKorea',
  CountryId.venezuela: 'venezuela',
  CountryId.afghanistan: 'afghanistan',
  CountryId.alandIslands: 'alandIslands',
  CountryId.americanSamoa: 'americanSamoa',
  CountryId.andorra: 'andorra',
  CountryId.angola: 'angola',
  CountryId.anguilla: 'anguilla',
  CountryId.antarctica: 'antarctica',
  CountryId.antiguaAndBarbuda: 'antiguaAndBarbuda',
  CountryId.armenia: 'armenia',
  CountryId.aruba: 'aruba',
  CountryId.bailiwickOfGuernsey: 'bailiwickOfGuernsey',
  CountryId.bailiwickOfJersey: 'bailiwickOfJersey',
  CountryId.barbados: 'barbados',
  CountryId.belarus: 'belarus',
  CountryId.belize: 'belize',
  CountryId.benin: 'benin',
  CountryId.bhutan: 'bhutan',
  CountryId.bonaireSaintEustatiusAndSaba: 'bonaireSaintEustatiusAndSaba',
  CountryId.botswana: 'botswana',
  CountryId.bouvetIsland: 'bouvetIsland',
  CountryId.britishIndianOceanTerritory: 'britishIndianOceanTerritory',
  CountryId.burkinaFaso: 'burkinaFaso',
  CountryId.burundi: 'burundi',
  CountryId.cameroon: 'cameroon',
  CountryId.capeVerde: 'capeVerde',
  CountryId.caribbeanNetherlands: 'caribbeanNetherlands',
  CountryId.caymanIslands: 'caymanIslands',
  CountryId.centralAfricanRepublic: 'centralAfricanRepublic',
  CountryId.chad: 'chad',
  CountryId.christmasIsland: 'christmasIsland',
  CountryId.cocosIslands: 'cocosIslands',
  CountryId.comoros: 'comoros',
  CountryId.congo: 'congo',
  CountryId.cookIslands: 'cookIslands',
  CountryId.cuba: 'cuba',
  CountryId.curacao: 'curacao',
  CountryId.democraticRepublicOfTheCongo: 'democraticRepublicOfTheCongo',
  CountryId.djibouti: 'djibouti',
  CountryId.dominica: 'dominica',
  CountryId.eastTimor: 'eastTimor',
  CountryId.equatorialGuinea: 'equatorialGuinea',
  CountryId.eritrea: 'eritrea',
  CountryId.ethiopia: 'ethiopia',
  CountryId.falklandIslands: 'falklandIslands',
  CountryId.faroeIslands: 'faroeIslands',
  CountryId.federatedStatesOfMicronesia: 'federatedStatesOfMicronesia',
  CountryId.fiji: 'fiji',
  CountryId.frenchGuiana: 'frenchGuiana',
  CountryId.frenchPolynesia: 'frenchPolynesia',
  CountryId.frenchSouthernTerritories: 'frenchSouthernTerritories',
  CountryId.gabon: 'gabon',
  CountryId.gambia: 'gambia',
  CountryId.gibraltar: 'gibraltar',
  CountryId.greenland: 'greenland',
  CountryId.grenada: 'grenada',
  CountryId.guadeloupe: 'guadeloupe',
  CountryId.guam: 'guam',
  CountryId.guinea: 'guinea',
  CountryId.guineaBissau: 'guineaBissau',
  CountryId.guyana: 'guyana',
  CountryId.heardIslandAndMcDonaldIslands: 'heardIslandAndMcDonaldIslands',
  CountryId.iran: 'iran',
  CountryId.iraq: 'iraq',
  CountryId.isleOfMan: 'isleOfMan',
  CountryId.ivoryCoast: 'ivoryCoast',
  CountryId.jamaica: 'jamaica',
  CountryId.kiribati: 'kiribati',
  CountryId.kyrgyzstan: 'kyrgyzstan',
  CountryId.laos: 'laos',
  CountryId.lebanon: 'lebanon',
  CountryId.lesotho: 'lesotho',
  CountryId.liberia: 'liberia',
  CountryId.libya: 'libya',
  CountryId.liechtenstein: 'liechtenstein',
  CountryId.macau: 'macau',
  CountryId.madagascar: 'madagascar',
  CountryId.malawi: 'malawi',
  CountryId.mali: 'mali',
  CountryId.marshallIslands: 'marshallIslands',
  CountryId.martinique: 'martinique',
  CountryId.mauritania: 'mauritania',
  CountryId.mayotte: 'mayotte',
  CountryId.moldova: 'moldova',
  CountryId.monaco: 'monaco',
  CountryId.mongolia: 'mongolia',
  CountryId.montserrat: 'montserrat',
  CountryId.mozambique: 'mozambique',
  CountryId.myanmar: 'myanmar',
  CountryId.namibia: 'namibia',
  CountryId.nauru: 'nauru',
  CountryId.nepal: 'nepal',
  CountryId.newCaledonia: 'newCaledonia',
  CountryId.niger: 'niger',
  CountryId.niue: 'niue',
  CountryId.norfolkIsland: 'norfolkIsland',
  CountryId.northernCyprus: 'northernCyprus',
  CountryId.northernMarianaIslands: 'northernMarianaIslands',
  CountryId.northKorea: 'northKorea',
  CountryId.northMacedonia: 'northMacedonia',
  CountryId.palau: 'palau',
  CountryId.palestine: 'palestine',
  CountryId.papuaNewGuinea: 'papuaNewGuinea',
  CountryId.pitcairn: 'pitcairn',
  CountryId.reunion: 'reunion',
  CountryId.rwanda: 'rwanda',
  CountryId.saintBarthelemy: 'saintBarthelemy',
  CountryId.saintHelenaAscensionAndTristianDaCunha:
      'saintHelenaAscensionAndTristianDaCunha',
  CountryId.saintKittsAndNevis: 'saintKittsAndNevis',
  CountryId.saintLucia: 'saintLucia',
  CountryId.saintMartin: 'saintMartin',
  CountryId.saintPierreAndMiquelon: 'saintPierreAndMiquelon',
  CountryId.saintVincentAndTheGrenadines: 'saintVincentAndTheGrenadines',
  CountryId.samoa: 'samoa',
  CountryId.sanMarino: 'sanMarino',
  CountryId.saoTomeAndPrincipe: 'saoTomeAndPrincipe',
  CountryId.senegal: 'senegal',
  CountryId.seychelles: 'seychelles',
  CountryId.sierraLeone: 'sierraLeone',
  CountryId.sintMaarten: 'sintMaarten',
  CountryId.solomonIslands: 'solomonIslands',
  CountryId.somalia: 'somalia',
  CountryId.southGeorgiaAndTheSouthSandwichIslands:
      'southGeorgiaAndTheSouthSandwichIslands',
  CountryId.southSudan: 'southSudan',
  CountryId.sudan: 'sudan',
  CountryId.suriname: 'suriname',
  CountryId.svalbardAndJanMayen: 'svalbardAndJanMayen',
  CountryId.eswatini: 'eswatini',
  CountryId.syria: 'syria',
  CountryId.tajikistan: 'tajikistan',
  CountryId.tanzania: 'tanzania',
  CountryId.togo: 'togo',
  CountryId.tokelau: 'tokelau',
  CountryId.tonga: 'tonga',
  CountryId.trinidadAndTobago: 'trinidadAndTobago',
  CountryId.turkmenistan: 'turkmenistan',
  CountryId.turksAndCaicosIslands: 'turksAndCaicosIslands',
  CountryId.tuvalu: 'tuvalu',
  CountryId.unitedStatesMinorOutlyingIslands:
      'unitedStatesMinorOutlyingIslands',
  CountryId.uzbekistan: 'uzbekistan',
  CountryId.vanuatu: 'vanuatu',
  CountryId.vaticanCity: 'vaticanCity',
  CountryId.virginIslandsBritish: 'virginIslandsBritish',
  CountryId.virginIslandsOfTheUnitedStates: 'virginIslandsOfTheUnitedStates',
  CountryId.wallisAndFutuna: 'wallisAndFutuna',
  CountryId.westernSahara: 'westernSahara',
  CountryId.yemen: 'yemen',
  CountryId.yugoslavia: 'yugoslavia',
  CountryId.zambia: 'zambia',
  CountryId.zimbabwe: 'zimbabwe',
  CountryId.schengenArea: 'schengenArea',
  CountryId.saintThomasAndPrince: 'saintThomasAndPrince',
};

const _$RegionIdEnumMap = {
  RegionId.none: 'none',
  RegionId.alabama: 'alabama',
  RegionId.alaska: 'alaska',
  RegionId.alberta: 'alberta',
  RegionId.arizona: 'arizona',
  RegionId.arkansas: 'arkansas',
  RegionId.australianCapitalTerritory: 'australianCapitalTerritory',
  RegionId.britishColumbia: 'britishColumbia',
  RegionId.california: 'california',
  RegionId.colorado: 'colorado',
  RegionId.connecticut: 'connecticut',
  RegionId.delaware: 'delaware',
  RegionId.districtOfColumbia: 'districtOfColumbia',
  RegionId.florida: 'florida',
  RegionId.georgia: 'georgia',
  RegionId.hawaii: 'hawaii',
  RegionId.idaho: 'idaho',
  RegionId.illinois: 'illinois',
  RegionId.indiana: 'indiana',
  RegionId.iowa: 'iowa',
  RegionId.kansas: 'kansas',
  RegionId.kentucky: 'kentucky',
  RegionId.louisiana: 'louisiana',
  RegionId.maine: 'maine',
  RegionId.manitoba: 'manitoba',
  RegionId.maryland: 'maryland',
  RegionId.massachusetts: 'massachusetts',
  RegionId.michigan: 'michigan',
  RegionId.minnesota: 'minnesota',
  RegionId.mississippi: 'mississippi',
  RegionId.missouri: 'missouri',
  RegionId.montana: 'montana',
  RegionId.nebraska: 'nebraska',
  RegionId.nevada: 'nevada',
  RegionId.newBrunswick: 'newBrunswick',
  RegionId.newHampshire: 'newHampshire',
  RegionId.newJersey: 'newJersey',
  RegionId.newMexico: 'newMexico',
  RegionId.newSouthWales: 'newSouthWales',
  RegionId.newYork: 'newYork',
  RegionId.northernTerritory: 'northernTerritory',
  RegionId.northCarolina: 'northCarolina',
  RegionId.northDakota: 'northDakota',
  RegionId.novaScotia: 'novaScotia',
  RegionId.ohio: 'ohio',
  RegionId.oklahoma: 'oklahoma',
  RegionId.ontario: 'ontario',
  RegionId.oregon: 'oregon',
  RegionId.pennsylvania: 'pennsylvania',
  RegionId.quebec: 'quebec',
  RegionId.queensland: 'queensland',
  RegionId.rhodeIsland: 'rhodeIsland',
  RegionId.saskatchewan: 'saskatchewan',
  RegionId.southAustralia: 'southAustralia',
  RegionId.southCarolina: 'southCarolina',
  RegionId.southDakota: 'southDakota',
  RegionId.tasmania: 'tasmania',
  RegionId.tennessee: 'tennessee',
  RegionId.texas: 'texas',
  RegionId.utah: 'utah',
  RegionId.vermont: 'vermont',
  RegionId.victoria: 'victoria',
  RegionId.virginia: 'virginia',
  RegionId.washington: 'washington',
  RegionId.westernAustralia: 'westernAustralia',
  RegionId.westVirginia: 'westVirginia',
  RegionId.wisconsin: 'wisconsin',
  RegionId.wyoming: 'wyoming',
  RegionId.yukon: 'yukon',
  RegionId.ciudadDeMexico: 'ciudadDeMexico',
  RegionId.jalisco: 'jalisco',
  RegionId.newfoundlandAndLabrador: 'newfoundlandAndLabrador',
  RegionId.nuevoLeon: 'nuevoLeon',
  RegionId.bajaCalifornia: 'bajaCalifornia',
  RegionId.chihuahua: 'chihuahua',
  RegionId.guanajuato: 'guanajuato',
  RegionId.guerrero: 'guerrero',
  RegionId.mexico: 'mexico',
  RegionId.michoacan: 'michoacan',
  RegionId.newYorkCity: 'newYorkCity',
  RegionId.tamaulipas: 'tamaulipas',
  RegionId.veracruz: 'veracruz',
  RegionId.chiapas: 'chiapas',
  RegionId.coahuila: 'coahuila',
  RegionId.durango: 'durango',
  RegionId.guerreroCocula: 'guerreroCocula',
  RegionId.guerreroJuchitan: 'guerreroJuchitan',
  RegionId.guerreroTepecoacuilco: 'guerreroTepecoacuilco',
  RegionId.guerreroTlacoapa: 'guerreroTlacoapa',
  RegionId.gujarat: 'gujarat',
  RegionId.hidalgo: 'hidalgo',
  RegionId.karnataka: 'karnataka',
  RegionId.kerala: 'kerala',
  RegionId.khyberPakhtunkhwa: 'khyberPakhtunkhwa',
  RegionId.madhyaPradesh: 'madhyaPradesh',
  RegionId.maharashtra: 'maharashtra',
  RegionId.morelos: 'morelos',
  RegionId.nayarit: 'nayarit',
  RegionId.oaxaca: 'oaxaca',
  RegionId.puebla: 'puebla',
  RegionId.punjab: 'punjab',
  RegionId.queretaro: 'queretaro',
  RegionId.sanLuisPotosi: 'sanLuisPotosi',
  RegionId.sinaloa: 'sinaloa',
  RegionId.sonora: 'sonora',
  RegionId.tabasco: 'tabasco',
  RegionId.tamilNadu: 'tamilNadu',
  RegionId.yucatan: 'yucatan',
  RegionId.zacatecas: 'zacatecas',
  RegionId.aguascalientes: 'aguascalientes',
  RegionId.bajaCaliforniaSur: 'bajaCaliforniaSur',
  RegionId.campeche: 'campeche',
  RegionId.colima: 'colima',
  RegionId.quintanaRooBenitoJuarez: 'quintanaRooBenitoJuarez',
  RegionId.quintanaRoo: 'quintanaRoo',
  RegionId.quintanaRooSolidaridad: 'quintanaRooSolidaridad',
  RegionId.tlaxcala: 'tlaxcala',
  RegionId.quintanaRooCozumel: 'quintanaRooCozumel',
  RegionId.saoPaolo: 'saoPaolo',
  RegionId.rioDeJaneiro: 'rioDeJaneiro',
  RegionId.rioGrandeDoSul: 'rioGrandeDoSul',
  RegionId.northwestTerritories: 'northwestTerritories',
  RegionId.nunavut: 'nunavut',
  RegionId.princeEdwardIsland: 'princeEdwardIsland',
  RegionId.distritoFederal: 'distritoFederal',
  RegionId.maranhao: 'maranhao',
  RegionId.matoGrosso: 'matoGrosso',
  RegionId.minasGerais: 'minasGerais',
  RegionId.para: 'para',
  RegionId.parana: 'parana',
  RegionId.pernambuco: 'pernambuco',
  RegionId.santaCatarina: 'santaCatarina',
  RegionId.andhraPradesh: 'andhraPradesh',
  RegionId.ceara: 'ceara',
  RegionId.goias: 'goias',
  RegionId.guerreroAcapulcoDeJuarez: 'guerreroAcapulcoDeJuarez',
  RegionId.haryana: 'haryana',
  RegionId.sergipe: 'sergipe',
  RegionId.alagoas: 'alagoas',
  RegionId.bangsamoro: 'bangsamoro',
  RegionId.telangana: 'telangana',
  RegionId.acre: 'acre',
  RegionId.espiritoSanto: 'espiritoSanto',
  RegionId.matoGrossoDoSul: 'matoGrossoDoSul',
  RegionId.paraiba: 'paraiba',
  RegionId.piaui: 'piaui',
  RegionId.rioGrandeDoNorte: 'rioGrandeDoNorte',
  RegionId.tocantins: 'tocantins',
  RegionId.odisha: 'odisha',
  RegionId.uttarakhand: 'uttarakhand',
};

const _$DocumentTypeIdEnumMap = {
  DocumentTypeId.none: 'none',
  DocumentTypeId.consularId: 'consularId',
  DocumentTypeId.dl: 'dl',
  DocumentTypeId.dlPublicServicesCard: 'dlPublicServicesCard',
  DocumentTypeId.employmentPass: 'employmentPass',
  DocumentTypeId.finCard: 'finCard',
  DocumentTypeId.id: 'id',
  DocumentTypeId.multipurposeId: 'multipurposeId',
  DocumentTypeId.myKad: 'myKad',
  DocumentTypeId.myKid: 'myKid',
  DocumentTypeId.myPr: 'myPr',
  DocumentTypeId.myTentera: 'myTentera',
  DocumentTypeId.panCard: 'panCard',
  DocumentTypeId.professionalId: 'professionalId',
  DocumentTypeId.publicServicesCard: 'publicServicesCard',
  DocumentTypeId.residencePermit: 'residencePermit',
  DocumentTypeId.residentId: 'residentId',
  DocumentTypeId.temporaryResidencePermit: 'temporaryResidencePermit',
  DocumentTypeId.voterId: 'voterId',
  DocumentTypeId.workPermit: 'workPermit',
  DocumentTypeId.iKad: 'iKad',
  DocumentTypeId.militaryId: 'militaryId',
  DocumentTypeId.myKas: 'myKas',
  DocumentTypeId.healthInsuranceCard: 'healthInsuranceCard',
  DocumentTypeId.passport: 'passport',
  DocumentTypeId.sPass: 'sPass',
  DocumentTypeId.addressCard: 'addressCard',
  DocumentTypeId.alienId: 'alienId',
  DocumentTypeId.alienPassport: 'alienPassport',
  DocumentTypeId.greenCard: 'greenCard',
  DocumentTypeId.minorsId: 'minorsId',
  DocumentTypeId.postalId: 'postalId',
  DocumentTypeId.professionalDl: 'professionalDl',
  DocumentTypeId.taxId: 'taxId',
  DocumentTypeId.weaponPermit: 'weaponPermit',
  DocumentTypeId.visa: 'visa',
  DocumentTypeId.borderCrossingCard: 'borderCrossingCard',
  DocumentTypeId.driverCard: 'driverCard',
  DocumentTypeId.globalEntryCard: 'globalEntryCard',
  DocumentTypeId.myPolis: 'myPolis',
  DocumentTypeId.nexusCard: 'nexusCard',
  DocumentTypeId.passportCard: 'passportCard',
  DocumentTypeId.proofOfAgeCard: 'proofOfAgeCard',
  DocumentTypeId.refugeeId: 'refugeeId',
  DocumentTypeId.tribalId: 'tribalId',
  DocumentTypeId.veteranId: 'veteranId',
  DocumentTypeId.citizenshipCertificate: 'citizenshipCertificate',
  DocumentTypeId.myNumberCard: 'myNumberCard',
  DocumentTypeId.consularPassport: 'consularPassport',
  DocumentTypeId.minorsPassport: 'minorsPassport',
  DocumentTypeId.minorsPublicServicesCard: 'minorsPublicServicesCard',
  DocumentTypeId.drivingPrivilegeCard: 'drivingPrivilegeCard',
  DocumentTypeId.asylumRequest: 'asylumRequest',
  DocumentTypeId.driverQualificationCard: 'driverQualificationCard',
  DocumentTypeId.provisionalDl: 'provisionalDl',
  DocumentTypeId.refugeePassport: 'refugeePassport',
  DocumentTypeId.specialId: 'specialId',
  DocumentTypeId.uniformedServicesId: 'uniformedServicesId',
  DocumentTypeId.immigrantVisa: 'immigrantVisa',
  DocumentTypeId.consularVoterId: 'consularVoterId',
  DocumentTypeId.twicCard: 'twicCard',
  DocumentTypeId.exitEntryPermit: 'exitEntryPermit',
  DocumentTypeId.mainlandTravelPermitTaiwan: 'mainlandTravelPermitTaiwan',
  DocumentTypeId.nbiClearance: 'nbiClearance',
  DocumentTypeId.proofOfRegistration: 'proofOfRegistration',
  DocumentTypeId.temporaryProtectionPermit: 'temporaryProtectionPermit',
  DocumentTypeId.afghanCitizenCard: 'afghanCitizenCard',
  DocumentTypeId.eid: 'eid',
  DocumentTypeId.pass: 'pass',
  DocumentTypeId.sisId: 'sisId',
  DocumentTypeId.asicCard: 'asicCard',
  DocumentTypeId.bidoonCard: 'bidoonCard',
  DocumentTypeId.interimHealthInsuranceCard: 'interimHealthInsuranceCard',
  DocumentTypeId.nonVoterId: 'nonVoterId',
  DocumentTypeId.reciprocalHealthInsuranceCard: 'reciprocalHealthInsuranceCard',
  DocumentTypeId.vehicleRegistration: 'vehicleRegistration',
  DocumentTypeId.esaadCard: 'esaadCard',
  DocumentTypeId.registrationCertificate: 'registrationCertificate',
  DocumentTypeId.medicalMarijuanaId: 'medicalMarijuanaId',
  DocumentTypeId.nonCardTribalId: 'nonCardTribalId',
  DocumentTypeId.diplomaticId: 'diplomaticId',
  DocumentTypeId.emergencyPassport: 'emergencyPassport',
  DocumentTypeId.temporaryPassport: 'temporaryPassport',
  DocumentTypeId.metisFederationCard: 'metisFederationCard',
  DocumentTypeId.socialSecurityCard: 'socialSecurityCard',
  DocumentTypeId.adrCertificate: 'adrCertificate',
  DocumentTypeId.ninCard: 'ninCard',
  DocumentTypeId.mySSSCard: 'mySSSCard',
  DocumentTypeId.gendarmerieId: 'gendarmerieId',
  DocumentTypeId.policeId: 'policeId',
  DocumentTypeId.originCard: 'originCard',
};

DocumentNumberRedactionSettings _$DocumentNumberRedactionSettingsFromJson(
  Map<String, dynamic> json,
) => DocumentNumberRedactionSettings(
  prefixDigitsVisible: (json['prefixDigitsVisible'] as num?)?.toInt(),
  suffixDigitsVisible: (json['suffixDigitsVisible'] as num?)?.toInt(),
);

Map<String, dynamic> _$DocumentNumberRedactionSettingsToJson(
  DocumentNumberRedactionSettings instance,
) => <String, dynamic>{
  'prefixDigitsVisible': instance.prefixDigitsVisible,
  'suffixDigitsVisible': instance.suffixDigitsVisible,
};
